### ISSUE TITLE
Create module to store "previously purchased" filter backend functionality

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce-archieve/vc-module-find-purchased#1]
Create solution with projects to store previously purchased module with backend functionality.
We would need product indexation extension to add "purchased_by" filter field to store array of the product purchasers (customerId). It would run on each product/catalog update/re-build index request.
We would need observer to execute on order creation to add customerId to the order's lineitem products index.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-115
